server:
    port: 8080
    compression:
        enabled: true
    codec:
        max-in-memory-size: 16MB  # Maximum size of in-memory buffer for compression

    shutdown: graceful  # WebServer Graceful shutdown (https://www.baeldung.com/spring-boot-web-server-shutdown)

spring:
    aot:
        enabled: true  # Enable AOT processing for Spring Boot applications

timefold:
    solver:
        termination:
            spent-limit: 30s  # The solver runs for 30 seconds. To run for 5 minutes use "5m" and for 2 hours use "2h".
    benchmark:
        solver:
            termination:
                spent-limit: 30s  # When benchmarking, each individual solver runs for 15 seconds. To run for 5 minutes use "5m" and for 2 hours use "2h".
