[versions]
bluetape4k-dependencies = "1.1.1"

[libraries]
bluetape4k-dependencies = { module = "io.github.bluetape4k:bluetape4k-dependencies", version.ref = "bluetape4k-dependencies" }
bluetape4k-coroutines = { module = "io.github.bluetape4k:bluetape4k-coroutines" }
exposed-core = { module = "io.github.bluetape4k.exposed:bluetape4k-exposed-core" }
exposed-dao = { module = "io.github.bluetape4k.exposed:bluetape4k-exposed-dao" }
exposed-jdbc-tests = { module = "io.github.bluetape4k.exposed:bluetape4k-exposed-jdbc-tests" }
exposed-r2dbc = { module = "io.github.bluetape4k.exposed:bluetape4k-exposed-r2dbc" }
exposed-r2dbc-tests = { module = "io.github.bluetape4k.exposed:bluetape4k-exposed-r2dbc-tests" }
bluetape4k-idgenerators = { module = "io.github.bluetape4k:bluetape4k-idgenerators" }
bluetape4k-io = { module = "io.github.bluetape4k:bluetape4k-io" }
bluetape4k-jackson2 = { module = "io.github.bluetape4k:bluetape4k-jackson2" }
bluetape4k-javatimes = { module = "io.github.bluetape4k:bluetape4k-javatimes" }
bluetape4k-junit5 = { module = "io.github.bluetape4k:bluetape4k-junit5" }
bluetape4k-logging = { module = "io.github.bluetape4k:bluetape4k-logging" }
bluetape4k-spring-boot3-core = { module = "io.github.bluetape4k:bluetape4k-spring-boot-core" }
bluetape4k-testcontainers = { module = "io.github.bluetape4k:bluetape4k-testcontainers" }
bluetape4k-timefold-solver-persistence-exposed = { module = "io.github.bluetape4k:bluetape4k-timefold-solver-persistence-exposed" }
