[versions]
bluetape4k = "1.8.0-SNAPSHOT"

[libraries]
bluetape4k-bom = { module = "io.github.bluetape4k:bluetape4k-bom", version.ref = "bluetape4k" }
bluetape4k-coroutines = { module = "io.github.bluetape4k:bluetape4k-coroutines", version.ref = "bluetape4k" }
exposed-core = { module = "io.github.bluetape4k.exposed:exposed-core", version.ref = "bluetape4k" }
exposed-dao = { module = "io.github.bluetape4k.exposed:exposed-dao", version.ref = "bluetape4k" }
exposed-jdbc-tests = { module = "io.github.bluetape4k.exposed:exposed-jdbc-tests", version.ref = "bluetape4k" }
exposed-r2dbc = { module = "io.github.bluetape4k.exposed:exposed-r2dbc", version.ref = "bluetape4k" }
exposed-r2dbc-tests = { module = "io.github.bluetape4k.exposed:exposed-r2dbc-tests", version.ref = "bluetape4k" }
bluetape4k-idgenerators = { module = "io.github.bluetape4k:bluetape4k-idgenerators", version.ref = "bluetape4k" }
bluetape4k-io = { module = "io.github.bluetape4k:bluetape4k-io", version.ref = "bluetape4k" }
bluetape4k-jackson2 = { module = "io.github.bluetape4k:bluetape4k-jackson2", version.ref = "bluetape4k" }
bluetape4k-javatimes = { module = "io.github.bluetape4k:bluetape4k-javatimes", version.ref = "bluetape4k" }
bluetape4k-junit5 = { module = "io.github.bluetape4k:bluetape4k-junit5", version.ref = "bluetape4k" }
bluetape4k-logging = { module = "io.github.bluetape4k:bluetape4k-logging", version.ref = "bluetape4k" }
bluetape4k-spring-boot3-core = { module = "io.github.bluetape4k:bluetape4k-spring-boot3-core", version.ref = "bluetape4k" }
bluetape4k-testcontainers = { module = "io.github.bluetape4k:bluetape4k-testcontainers", version.ref = "bluetape4k" }
bluetape4k-timefold-solver-persistence-exposed = { module = "io.github.bluetape4k:bluetape4k-timefold-solver-persistence-exposed", version.ref = "bluetape4k" }
