gantt
    title Test Execution Timeline
    dateFormat YYYY-MM-DDTHH:mm:ss.SSS
    axisFormat %H:%M:%S
    section timefold.workshop.school.timetabling.controller.TimetableControllerTest
        SMALL(✅): active, 2025-06-02T10:04:02.722180Z, 523ms
        LARGE(✅): active, 2025-06-02T10:04:03.246378Z, 65ms
        SMALL(✅): active, 2025-06-02T10:04:03.313097Z, 1146ms
        LARGE(✅): active, 2025-06-02T10:04:04.460159Z, 1043ms
    section timefold.workshop.school.timetabling.controller.TimetableEnvironmentTest
        solve full assert()(✅): active, 2025-06-02T10:04:05.685310Z, 30017ms
        solve step assert()(✅): active, 2025-06-02T10:04:35.703306Z, 30006ms
    section timefold.workshop.school.timetabling.solver.TimetableConstraintProviderTest
        teacher conflict()(✅): active, 2025-06-02T10:05:05.835601Z, 5ms
        student group conflict()(✅): active, 2025-06-02T10:05:05.840722Z, 0ms
        teacher time efficiency()(✅): active, 2025-06-02T10:05:05.841736Z, 0ms
        room conflit()(✅): active, 2025-06-02T10:05:05.842709Z, 1ms
        teacher room stability()(✅): active, 2025-06-02T10:05:05.844778Z, 2ms
        학생들은 교과목의 다양성을 가져야 합니다()(✅): active, 2025-06-02T10:05:05.847223Z, 1ms
